spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            auto:
              offset:
                reset: earliest
      bindings:
        poll-in-0:
          destination: transaction-topic
          group: transaction-group
